services:
  - type: web
    name: gymmanagement
    env: python
    plan: free
    runtime: python
    pythonVersion: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn GymManagementDjango.wsgi:application
